<a href="https://colab.research.google.com/github/SaiDhanyaa/ExcelR_Assignments/blob/main/ASSIGNMENT_14_SVM_FOREST_FIRES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

classify the Size_Categorie using SVM

month	month of the year: 'jan' to 'dec'
day	day of the week: 'mon' to 'sun'
FFMC	FFMC index from the FWI system: 18.7 to 96.20
DMC	DMC index from the FWI system: 1.1 to 291.3
DC	DC index from the FWI system: 7.9 to 860.6
ISI	ISI index from the FWI system: 0.0 to 56.10
temp	temperature in Celsius degrees: 2.2 to 33.30
RH	relative humidity in %: 15.0 to 100
wind	wind speed in km/h: 0.40 to 9.40
rain	outside rain in mm/m2 : 0.0 to 6.4
Size_Categorie 	the burned area of the forest ( Small , Large)


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score

In [ ]:
# # Load Dataset

fire= pd.read_csv("/content/forestfires.csv")
fire.head(10)

month  day  FFMC    DMC  ...  monthnov  monthoct  monthsep  size_category
0   mar  fri  86.2   26.2  ...         0         0         0          small
1   oct  tue  90.6   35.4  ...         0         1         0          small
2   oct  sat  90.6   43.7  ...         0         1         0          small
3   mar  fri  91.7   33.3  ...         0         0         0          small
4   mar  sun  89.3   51.3  ...         0         0         0          small
5   aug  sun  92.3   85.3  ...         0         0         0          small
6   aug  mon  92.3   88.9  ...         0         0         0          small
7   aug  mon  91.5  145.4  ...         0         0         0          small
8   sep  tue  91.0  129.5  ...         0         0         1          small
9   sep  sat  92.5   88.0  ...         0         0         1          small

[10 rows x 31 columns]

In [ ]:
# # Preprocessing & Label Encoding 

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
fire["month"] = label_encoder.fit_transform(fire["month"])
fire["day"] = label_encoder.fit_transform(fire["day"])
fire["size_category"] = label_encoder.fit_transform(fire["size_category"])


In [ ]:
fire.head(10)

month  day  FFMC    DMC  ...  monthnov  monthoct  monthsep  size_category
0      7    0  86.2   26.2  ...         0         0         0              1
1     10    5  90.6   35.4  ...         0         1         0              1
2     10    2  90.6   43.7  ...         0         1         0              1
3      7    0  91.7   33.3  ...         0         0         0              1
4      7    3  89.3   51.3  ...         0         0         0              1
5      1    3  92.3   85.3  ...         0         0         0              1
6      1    1  92.3   88.9  ...         0         0         0              1
7      1    1  91.5  145.4  ...         0         0         0              1
8     11    5  91.0  129.5  ...         0         0         1              1
9     11    2  92.5   88.0  ...         0         0         1              1

[10 rows x 31 columns]

In [ ]:
X=fire.iloc[:,:11]
X

In [ ]:
Y=fire["size_category"]
Y

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.3)
 

In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((361, 11), (361,), (156, 11), (156,))

## **KERNEL: rbf**

In [ ]:
### Grid Search CV..  TO KNO WHICH KERNEL AND WHICH GAMMA VALUE IS BEST, GO FOR GRID SEARCH BY GIVING RANGE OF GAMMA VALUES..
clf = SVC()
param_grid = [{'kernel':['rbf'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

In [ ]:
gsv.best_params_ , gsv.best_score_   #### this gives the best gamma value and kernel

({'C': 15, 'gamma': 0.5, 'kernel': 'rbf'}, 0.7423423423423424)

In [ ]:
clf = SVC(C= 15, gamma = 0.5)
clf.fit(X_train , y_train)    ####build thhe model
y_pred = clf.predict(X_test)     #### then go for prediction
acc = accuracy_score(y_test, y_pred) * 100     #### then find the accuracy
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 72.43589743589743


array([[  1,  43],
       [  0, 112]])

## **KERNEL: Poly**

In [ ]:
### Poly

clf2 = SVC()
param_grid = [{'kernel':['poly'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=15, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3, gamma=0.5,
                           kernel='rbf', max_iter=-1, probability=False,
                           random_state=None, shrinking=True, tol=0.001,
                           verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['poly']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
gsv.best_params_ , gsv.best_score_

({'C': 15, 'gamma': 50, 'kernel': 'poly'}, 0.9833333333333334)

In [ ]:
clf = SVC(C= 15, gamma = 50)
clf.fit(X_train , y_train)    ####build thhe model
y_pred = clf.predict(X_test)     #### then go for prediction
acc = accuracy_score(y_test, y_pred) * 100     #### then find the accuracy
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 71.7948717948718


array([[  0,  44],
       [  0, 112]])

## **KERNEL: Sigmoid**

In [ ]:
# Sigmoid

clf3 = SVC()
param_grid = [{'kernel':['sigmoid'],'gamma':[50,5,10,0.5],'C':[15,14,13,12,11,10,0.1,0.001] }]
gsv = GridSearchCV(clf,param_grid,cv=10)
gsv.fit(X_train,y_train)


GridSearchCV(cv=10, error_score=nan,
             estimator=SVC(C=15, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3, gamma=50,
                           kernel='rbf', max_iter=-1, probability=False,
                           random_state=None, shrinking=True, tol=0.001,
                           verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [15, 14, 13, 12, 11, 10, 0.1, 0.001],
                          'gamma': [50, 5, 10, 0.5], 'kernel': ['sigmoid']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
gsv.best_params_ , gsv.best_score_

({'C': 15, 'gamma': 50, 'kernel': 'sigmoid'}, 0.7368618618618619)

In [ ]:
clf = SVC(C= 15, gamma = 50)
clf.fit(X_train , y_train)    ####build thhe model
y_pred = clf.predict(X_test)     #### then go for prediction
acc = accuracy_score(y_test, y_pred) * 100     #### then find the accuracy
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 71.7948717948718


array([[  0,  44],
       [  0, 112]])